apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-dev
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/dev/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
